### PR TITLE
Rename "alone" > "mono" in configuration file and internal variables

### PR DESCRIPTION
**Pull request by dfelinto**
Note: This change requires that old XML files be updated

...

Hi @touraine (and anyone else) any objections to this change? I'm under the impression that 'mono' is a more known term than 'alone' when it comes to that.

### CODE REVIEW

**Comment by bfgkatz** [comment]
Is this a question of 1 user / multiple users or 1 mono/stereoscopic rendering?

-Brian FG Katz
LIMSI-CNRS

**Comment by dfelinto** [comment]
From what I got is a question of mono/left/right, see 'alone' here:
http://blendervr.limsi.fr/doku.php?id=doc:config

**Comment by bfgkatz** [comment]
From that use it would seem "mono" would be more correct, or "none" if no buffer is actually used in that case.

**Comment by dfelinto** [comment]
@laurent @touraine @PyrApple @occamjmv I'm pushing this to master. Which now means any xml config file you may be using that was using the 'alone' mode, should now use 'mono'.

**Pull request merged**
